// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;

# Represents the Queries record for the operation: getTimeSeriesForAllUSAStatesNYT
public type GetTimeSeriesForAllUSAStatesNYTQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

# Represents the Queries record for the operation: getVaccineCoverageOfAllUSAStates
public type GetVaccineCoverageOfAllUSAStatesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
    # Flag indicating whether to return data type as SimpleVaccineTimeline (false) or FullVaccineTimeline (true)
    string fullData = "false";
};

public type CovidState record {
    string state;
    decimal updated;
    decimal cases;
    decimal todayCases;
    decimal deaths;
    decimal todayDeaths;
    decimal active;
    decimal casesPerOneMillion?;
    decimal deathsPerOneMillion?;
    decimal tests?;
    decimal testsPerOneMillion?;
    decimal population;
};

public type CovidCountry record {
    decimal updated?;
    string country;
    CovidCountryCountryInfo countryInfo?;
    decimal cases;
    decimal todayCases;
    decimal deaths;
    decimal todayDeaths;
    decimal recovered;
    decimal todayRecovered?;
    decimal active;
    decimal critical?;
    decimal casesPerOneMillion?;
    decimal deathsPerOneMillion?;
    decimal tests?;
    decimal testsPerOneMillion?;
    decimal population;
    string continent;
    decimal oneCasePerPeople?;
    decimal oneDeathPerPeople?;
    decimal oneTestPerPeople?;
    decimal activePerOneMillion?;
    decimal recoveredPerOneMillion?;
    decimal criticalPerOneMillion?;
};

# Represents the Queries record for the operation: getUSAStatusByState
public type GetUSAStatusByStateQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
};

public type CovidHistoricalInner record {
    string country;
    string? province?;
    Timeline timeline;
};

public type Vaccines record {
    string 'source?;
    string totalCandidates?;
    Phases[] phases?;
    Vaccine[] data?;
};

public type InfluenzaILINet record {
    decimal updated?;
    string 'source?;
    ILINet[] data?;
};

# Represents the Queries record for the operation: getAllCountriesStatus
public type GetAllCountriesStatusQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
    # Provided a key (e.g. cases, todayCases, deaths, recovered, active), the result will be sorted from greatest to least
    "cases"|"todayCases"|"deaths"|"todayDeaths"|"recovered"|"active"|"critical"|"casesPerOneMillion"|"deathsPerOneMillion" sort?;
};

public type TimelineDeaths record {
    decimal date?;
};

# Represents the Queries record for the operation: getAllContinentsStatus
public type GetAllContinentsStatusQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
    # Provided a key (e.g. cases, todayCases, deaths, recovered, active), results will be sorted from greatest to least
    "cases"|"todayCases"|"deaths"|"todayDeaths"|"recovered"|"active"|"critical"|"casesPerOneMillion"|"deathsPerOneMillion" sort?;
};

public type CovidContinent record {
    decimal updated;
    decimal cases;
    decimal todayCases;
    decimal deaths;
    decimal todayDeaths;
    decimal recovered?;
    decimal todayRecovered?;
    decimal active;
    decimal critical;
    decimal casesPerOneMillion?;
    decimal deathsPerOneMillion?;
    decimal tests?;
    decimal testsPerOneMillion?;
    decimal population?;
    string continent?;
    decimal activePerOneMillion?;
    decimal recoveredPerOneMillion?;
    decimal criticalPerOneMillion?;
    CovidContinentContinentInfo continentInfo?;
    string[] countries?;
};

public type CovidAppleSubregions record {
    string country?;
    string[] subregions?;
};

public type CovidNYTCountyInner record {
    string date?;
    decimal cases?;
    string county?;
    string fips?;
    string state?;
    decimal deaths?;
};

public type CovidNYTUSAInner record {
    string date?;
    decimal cases?;
    decimal deaths?;
};

public type Phases record {
    string phase?;
    string candidates?;
};

public type CovidHistoricalUSCounty CovidHistoricalUSCountyInner[];

# Represents the Queries record for the operation: getGovernmentReportedDataByCountry
public type GetGovernmentReportedDataByCountryQueries record {
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
};

public type CovidHistoricalUSCountyInner record {
    string province?;
    string county?;
    Timeline timeline?;
};

public type CovidJHUCountryStats record {
    decimal? recovered?;
    decimal confirmed;
    decimal deaths;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type USCL record {
    string week?;
    decimal totalA?;
    decimal totalB?;
    decimal percentPositiveA?;
    decimal percentPositiveB?;
    decimal totalTests?;
    decimal percentPositive?;
};

public type CovidContinentContinentInfo record {
    decimal lat?;
    decimal long?;
};

public type USPHL record {
    string week?;
    decimal A\(H3N2v\)?;
    decimal A\(H1N1\)?;
    decimal A\(H3\)?;
    decimal A\(unable\ to\ sub\-type\)\+?;
    decimal A\(Subtyping\ not\ performed\)?;
    decimal B?;
    decimal BVIC?;
    decimal totalTests?;
};

# Represents the Queries record for the operation: getUSACountiesDataByState
public type GetUSACountiesDataByStateQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

public type InfluenzaUSCL record {
    decimal updated?;
    string 'source?;
    USCL[] data?;
};

# Represents the Queries record for the operation: getTimeSeriesDataForMultipleProvinces
public type GetTimeSeriesDataForMultipleProvincesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

# Represents the Queries record for the operation: getTimeSeriesBycountry
public type GetTimeSeriesBycountryQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

# Represents the Queries record for the operation: getTimeSeriesForAllCountriesAndProvinces
public type GetTimeSeriesForAllCountriesAndProvincesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

public type CovidHistoricalProvinces CovidHistoricalProvince[];

public type CovidNYTUSA CovidNYTUSAInner[];

public type InfluenzaUSPHL record {
    decimal updated?;
    string 'source?;
    USPHL[] data?;
};

# Represents the Queries record for the operation: getStatusByCountry
public type GetStatusByCountryQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
    # Setting to false gives you the ability to fuzzy search countries (i.e. Oman vs. rOMANia)
    "true"|"false" strict = "true";
};

public type FullVaccineTimelineInner record {
    string date?;
    decimal total?;
    decimal daily?;
    decimal dailyPerMillion?;
    decimal totalPerHundred?;
};

public type CovidCountryCountryInfo record {
    string flag?;
    @jsondata:Name {value: "_id"}
    decimal? id?;
    string? iso2?;
    decimal lat?;
    decimal long?;
    string? iso3?;
};

public type CovidHistoricalAll record {
    TimelineDeaths cases;
    TimelineDeaths deaths;
    TimelineDeaths recovered;
};

# Represents the Queries record for the operation: getStatusByContinent
public type GetStatusByContinentQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
    # Setting to false gives you the ability to fuzzy search continents (i.e. Oman vs. rOMANia)
    "true"|"false" strict = "true";
};

public type CovidContinents CovidContinent[];

# Represents the Queries record for the operation: getTimeSeriesByProvince
public type GetTimeSeriesByProvinceQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

# Represents the Queries record for the operation: getTimeSeriesByUSAStateNYT
public type GetTimeSeriesByUSAStateNYTQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

public type CovidHistoricalCountry record {
    string country?;
    string[] province?;
    Timeline timeline?;
};

public type Therapeutics record {
    string 'source?;
    string totalCandidates?;
    Phases[] phases?;
    Therapeutic[] data?;
};

public type CovidJHUCountry record {
    string country;
    string? county?;
    string updatedAt?;
    CovidJHUCountryStats stats;
    CovidJHUCountryCoordinates coordinates?;
    string? province?;
};

public type CovidNYTCounty CovidNYTCountyInner[];

public type CovidJHUCountries CovidJHUCountry[];

public type VaccineStatesCoverage VaccineStateCoverage[];

public type VaccineCoverage SimpleVaccineTimeline|FullVaccineTimeline;

# Represents the Queries record for the operation: getGlobalStatus
public type GetGlobalStatusQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
};

public type CovidHistoricalUSCounties string[];

public type CovidAppleDataData record {
    string date?;
    @jsondata:Name {value: "geo_type"}
    string geoType?;
    decimal driving?;
    decimal transit?;
    decimal walking?;
    @jsondata:Name {value: "subregion_and_city"}
    string subregionAndCity?;
    @jsondata:Name {value: "sub-region"}
    string subRegion?;
};

public type CovidAll record {
    decimal updated;
    decimal cases;
    decimal todayCases;
    decimal deaths;
    decimal todayDeaths;
    decimal recovered;
    decimal todayRecovered;
    decimal active;
    decimal critical;
    decimal casesPerOneMillion?;
    decimal deathsPerOneMillion?;
    decimal tests?;
    decimal testsPerOneMillion?;
    decimal population;
    decimal oneCasePerPeople?;
    decimal oneDeathPerPeople?;
    decimal oneTestPerPeople?;
    decimal activePerOneMillion?;
    decimal recoveredPerOneMillion?;
    decimal criticalPerOneMillion?;
    decimal affectedCountries?;
};

# Represents the Queries record for the operation: getVaccineCoverageByCountry
public type GetVaccineCoverageByCountryQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
    # Flag indicating whether to return data type as SimpleVaccineTimeline (false) or FullVaccineTimeline (true)
    string fullData = "false";
};

public type CovidAppleData record {
    string country?;
    string subregion?;
    CovidAppleDataData[] data?;
};

public type CovidAppleCountries string[];

# Represents the Queries record for the operation: getVaccineCoverageByUSAState
public type GetVaccineCoverageByUSAStateQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
    # Flag indicating whether to return data type as SimpleVaccineTimeline (false) or FullVaccineTimeline (true)
    string fullData = "false";
};

# Represents the Queries record for the operation: getMultipleCountriesStatus
public type GetMultipleCountriesStatusQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # Enter `true`(1) to receive data reported two days ago. Default is `false`(0)
    "true"|"false"|"1"|"0" twoDaysAgo?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
};

public type VaccineCountryCoverage record {
    string country?;
    SimpleVaccineTimeline|FullVaccineTimeline timeline?;
};

public type ILINet record {
    string week?;
    decimal age\ 5\-24?;
    decimal age\ 25\-49?;
    decimal age\ 50\-64?;
    decimal age\ 64\+?;
    decimal totalILI?;
    decimal totalPatients?;
    decimal percentUnweightedILI?;
    decimal percentWeightedILI?;
};

public type CovidJHUCountryCoordinates record {
    string latitude?;
    string longitude?;
};

public type VaccineCountriesCoverage VaccineCountryCoverage[];

public type CovidStates CovidState[];

public type CovidNYTStateInner record {
    string date;
    decimal cases;
    string fips;
    string state;
    decimal deaths;
};

public type CovidGov string[];

# Represents the Queries record for the operation: getAllUSAStatesStatus
public type GetAllUSAStatesStatusQueries record {
    # Enter `true`(1) to receive data reported a day ago. Default is `false`(0)
    "true"|"false"|"1"|"0" yesterday?;
    # By default, value is 0. Enter `1` to allow nulls to be returned
    "true"|"false"|"1"|"0" allowNull?;
    # Provided a key (e.g. cases, todayCases, deaths, active), result will be sorted from greatest to least
    "cases"|"todayCases"|"deaths"|"todayDeaths"|"active" sort?;
};

public type CovidCountries CovidCountry[];

# Represents the Queries record for the operation: getTimeSeriesByUSACountyNYT
public type GetTimeSeriesByUSACountyNYTQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

public type FullVaccineTimeline FullVaccineTimelineInner[];

# Represents the Queries record for the operation: getGlobalStatusInTimeSeries
public type GetGlobalStatusInTimeSeriesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

# Represents the Queries record for the operation: getTimeSeriesOfMultipleCountries
public type GetTimeSeriesOfMultipleCountriesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
};

public type Therapeutic record {
    string medicationClass?;
    string[] tradeName?;
    string details?;
    string[] developerResearcher?;
    string[] sponsors?;
    string trialPhase?;
    string lastUpdate?;
};

public type Vaccine record {
    string candidate?;
    string mechanism?;
    string[] sponsors?;
    string details?;
    string trialPhase?;
    string[] institutions?;
};

# Represents the Queries record for the operation: getTotalGlobalVaccineDosesAdministered
public type GetTotalGlobalVaccineDosesAdministeredQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
    # Flag indicating whether to return data type as SimpleVaccineTimeline (false) or FullVaccineTimeline (true)
    string fullData = "false";
};

public type CovidHistorical CovidHistoricalInner[];

public type CovidJHUCounty record {
    string country;
    string province;
    string county;
    string updatedAt?;
    CovidJHUCountryStats stats?;
    CovidJHUCountryCoordinates coordinates?;
};

public type CovidJHUCounties CovidJHUCounty[];

public type CovidHistoricalProvince record {
    string country?;
    string province?;
    Timeline timeline?;
};

# Represents the Queries record for the operation: getVaccineCoverageOfAllCountries
public type GetVaccineCoverageOfAllCountriesQueries record {
    # Number of days to return. Use 'all' for the full data set (e.g. 15, all, 24)
    string lastdays = "30";
    # Flag indicating whether to return data type as SimpleVaccineTimeline (false) or FullVaccineTimeline (true)
    string fullData = "false";
};

public type Timeline record {
    TimelineDeaths recovered;
    Cases cases;
    TimelineDeaths deaths;
};

public type CovidHistoricalCountries CovidHistoricalCountry[];

public type VaccineStateCoverage record {
    SimpleVaccineTimeline|FullVaccineTimeline timeline?;
    string state?;
};

public type CovidNYTState CovidNYTStateInner[];

public type SimpleVaccineTimeline record {
    decimal date?;
};

public type Cases record {
    decimal date?;
};
